const locales = {
  es: {
    bold: 'Negrita',
    italic: 'Cursiva',
    underline: 'Subrayado',
    strikethrough: 'Tachado',
    heading: 'Encabezado',
    fontFamily: 'Fuente',
    fontSearchPlaceholder: 'Buscar fuente...',
    search: 'Buscar en el editor',
    searchPlaceholder: 'Buscar texto...',
    searchEmpty: 'Sin resultados',
    searchResults: 'resultados',
    heading1: 'Encabezado 1',
    heading2: 'Encabezado 2',
    heading3: 'Encabezado 3',
    heading4: 'Encabezado 4',
    heading5: 'Encabezado 5',
    heading6: 'Encabezado 6',
    paragraph: 'Párrafo',
    orderedList: 'Lista ordenada',
    unorderedList: 'Lista desordenada',
    alignLeft: 'Alinear izquierda',
    alignCenter: 'Centrar',
    alignRight: 'Alinear derecha',
    alignJustify: 'Justificar',
    link: 'Insertar enlace',
    unlink: 'Quitar enlace',
    image: 'Insertar imagen',
    blockquote: 'Cita',
    codeBlock: 'Bloque de código',
    code: 'Código',
    horizontalRule: 'Línea horizontal',
    textColor: 'Color de texto',
    backgroundColor: 'Color de fondo',
    undo: 'Deshacer',
    redo: 'Rehacer',
    removeFormat: 'Limpiar formato',
    sourceView: 'Vista HTML',
    fullscreen: 'Pantalla completa',
    linkDialogTitle: 'Insertar enlace',
    linkDialogUrl: 'URL',
    linkDialogText: 'Texto',
    linkDialogTarget: 'Abrir en nueva pestaña',
    linkDialogCancel: 'Cancelar',
    linkDialogApply: 'Aplicar',
    imageDialogTitle: 'Insertar imagen',
    imageUploadTab: 'Subir archivo',
    imageUrlTab: 'Configuración',
    imageDialogUrl: 'URL de la imagen',
    imageDialogAlt: 'Texto alternativo',
    imageWidth: 'Ancho',
    imageHeight: 'Alto',
    imageUploadBtn: 'Subir al servidor',
    imageDropHint: 'Arrastra una imagen o haz clic para seleccionar',
    imageUploadError: 'Error al subir la imagen',
    imageDialogCancel: 'Cancelar',
    imageDialogApply: 'Insertar',
    alignLeft: 'Alinear izquierda',
    alignCenter: 'Centrar',
    alignRight: 'Alinear derecha',
    sourceDialogTitle: 'Editar HTML',
    sourceDialogCancel: 'Cancelar',
    sourceDialogApply: 'Guardar',
    placeholder: 'Escribe aquí...',
  },
  en: {
    bold: 'Bold',
    italic: 'Italic',
    underline: 'Underline',
    strikethrough: 'Strikethrough',
    heading: 'Heading',
    fontFamily: 'Font',
    fontSearchPlaceholder: 'Search font...',
    search: 'Search editor',
    searchPlaceholder: 'Search text...',
    searchEmpty: 'No results',
    searchResults: 'results',
    heading1: 'Heading 1',
    heading2: 'Heading 2',
    heading3: 'Heading 3',
    heading4: 'Heading 4',
    heading5: 'Heading 5',
    heading6: 'Heading 6',
    paragraph: 'Paragraph',
    orderedList: 'Ordered list',
    unorderedList: 'Unordered list',
    alignLeft: 'Align left',
    alignCenter: 'Center',
    alignRight: 'Align right',
    alignJustify: 'Justify',
    link: 'Insert link',
    unlink: 'Remove link',
    image: 'Insert image',
    blockquote: 'Blockquote',
    codeBlock: 'Code block',
    code: 'Code',
    horizontalRule: 'Horizontal rule',
    textColor: 'Text color',
    backgroundColor: 'Background color',
    undo: 'Undo',
    redo: 'Redo',
    removeFormat: 'Remove format',
    sourceView: 'HTML source',
    fullscreen: 'Fullscreen',
    linkDialogTitle: 'Insert link',
    linkDialogUrl: 'URL',
    linkDialogText: 'Text',
    linkDialogTarget: 'Open in new tab',
    linkDialogCancel: 'Cancel',
    linkDialogApply: 'Apply',
    imageDialogTitle: 'Insert image',
    imageUploadTab: 'Upload file',
    imageUrlTab: 'Settings',
    imageDialogUrl: 'Image URL',
    imageDialogAlt: 'Alt text',
    imageWidth: 'Width',
    imageHeight: 'Height',
    imageUploadBtn: 'Upload to server',
    imageDropHint: 'Drop an image or click to select',
    imageUploadError: 'Error uploading image',
    imageDialogCancel: 'Cancel',
    imageDialogApply: 'Insert',
    alignLeft: 'Align left',
    alignCenter: 'Center',
    alignRight: 'Align right',
    sourceDialogTitle: 'Edit HTML',
    sourceDialogCancel: 'Cancel',
    sourceDialogApply: 'Save',
    placeholder: 'Type here...',
  },
};

export function t(key, locale = 'es') {
  return locales[locale]?.[key] || locales.es[key] || key;
}
