const locales = {
  es: {
    bold: 'Negrita',
    italic: 'Cursiva',
    underline: 'Subrayado',
    strikethrough: 'Tachado',
    heading: 'Encabezado',
    fontFamily: 'Fuente',
    fontSearchPlaceholder: 'Buscar fuente...',
    search: 'Buscar en el editor',
    searchPlaceholder: 'Buscar texto...',
    searchEmpty: 'Sin resultados',
    searchResults: 'resultados',
    heading1: 'Encabezado 1',
    heading2: 'Encabezado 2',
    heading3: 'Encabezado 3',
    heading4: 'Encabezado 4',
    heading5: 'Encabezado 5',
    heading6: 'Encabezado 6',
    paragraph: 'Párrafo',
    orderedList: 'Lista ordenada',
    unorderedList: 'Lista desordenada',
    alignLeft: 'Alinear izquierda',
    alignCenter: 'Centrar',
    alignRight: 'Alinear derecha',
    alignJustify: 'Justificar',
    link: 'Insertar enlace',
    unlink: 'Quitar enlace',
    image: 'Insertar imagen',
    table: 'Insertar tabla',
    tablePickerHint: 'Seleccione el tamaño de la tabla',
    tablePickerSize: 'Tabla {cols} × {rows}',
    tableHeaderRow: 'Fila de encabezado',
    tableRows: 'Filas',
    tableCols: 'Columnas',
    tableInsertCustom: 'Insertar',
    tableInsertRowAbove: 'Insertar fila arriba',
    tableInsertRowBelow: 'Insertar fila abajo',
    tableInsertColumnLeft: 'Insertar columna a la izquierda',
    tableInsertColumnRight: 'Insertar columna a la derecha',
    tableDeleteRow: 'Eliminar fila',
    tableDeleteColumn: 'Eliminar columna',
    tableDeleteTable: 'Eliminar tabla',
    blockquote: 'Cita',
    blockquoteExitHint: 'Pulsa Enter en una línea vacía para continuar fuera de la cita',
    codeBlock: 'Bloque de código',
    code: 'Código',
    horizontalRule: 'Línea horizontal',
    textColor: 'Color de texto',
    backgroundColor: 'Color de fondo',
    undo: 'Deshacer',
    redo: 'Rehacer',
    removeFormat: 'Limpiar formato',
    sourceView: 'Vista HTML',
    fullscreen: 'Pantalla completa',
    linkDialogTitle: 'Insertar enlace',
    linkDialogUrl: 'URL',
    linkDialogText: 'Texto',
    linkDialogTarget: 'Abrir en nueva pestaña',
    linkDialogCancel: 'Cancelar',
    linkDialogApply: 'Aplicar',
    imageDialogTitle: 'Insertar imagen',
    imageUploadTab: 'Subir archivo',
    imageUrlTab: 'Configuración',
    imageDialogUrl: 'URL de la imagen',
    imageDialogAlt: 'Texto alternativo',
    imageWidth: 'Ancho',
    imageHeight: 'Alto',
    imageUploadBtn: 'Subir al servidor',
    imageDropHint: 'Arrastra una imagen o haz clic para seleccionar',
    imageUploadError: 'Error al subir la imagen',
    imageDialogCancel: 'Cancelar',
    imageDialogApply: 'Insertar',
    alignLeft: 'Alinear izquierda',
    alignCenter: 'Centrar',
    alignRight: 'Alinear derecha',
    sourceDialogTitle: 'Editar HTML',
    sourceDialogCancel: 'Cancelar',
    sourceDialogApply: 'Guardar',
    placeholder: 'Escribe aquí...',
    exportPdfTitle: 'Documento Aracode',
    exportPdfEmpty: 'No hay contenido para exportar a PDF.',
    exportPdfError: 'No se pudo exportar el PDF.',
    exportPdf: 'Exportar PDF',
    exportPdfFilename: 'documento-aracode.pdf',
    exportPdfPrintHint: 'Se abrió el diálogo de impresión. Elija "Guardar como PDF" como destino.',
  },
  en: {
    bold: 'Bold',
    italic: 'Italic',
    underline: 'Underline',
    strikethrough: 'Strikethrough',
    heading: 'Heading',
    fontFamily: 'Font',
    fontSearchPlaceholder: 'Search font...',
    search: 'Search editor',
    searchPlaceholder: 'Search text...',
    searchEmpty: 'No results',
    searchResults: 'results',
    heading1: 'Heading 1',
    heading2: 'Heading 2',
    heading3: 'Heading 3',
    heading4: 'Heading 4',
    heading5: 'Heading 5',
    heading6: 'Heading 6',
    paragraph: 'Paragraph',
    orderedList: 'Ordered list',
    unorderedList: 'Unordered list',
    alignLeft: 'Align left',
    alignCenter: 'Center',
    alignRight: 'Align right',
    alignJustify: 'Justify',
    link: 'Insert link',
    unlink: 'Remove link',
    image: 'Insert image',
    table: 'Insert table',
    tablePickerHint: 'Select table size',
    tablePickerSize: '{cols} × {rows} Table',
    tableHeaderRow: 'Header row',
    tableRows: 'Rows',
    tableCols: 'Columns',
    tableInsertCustom: 'Insert',
    tableInsertRowAbove: 'Insert row above',
    tableInsertRowBelow: 'Insert row below',
    tableInsertColumnLeft: 'Insert column to the left',
    tableInsertColumnRight: 'Insert column to the right',
    tableDeleteRow: 'Delete row',
    tableDeleteColumn: 'Delete column',
    tableDeleteTable: 'Delete table',
    blockquote: 'Blockquote',
    blockquoteExitHint: 'Press Enter on an empty line to continue below the quote',
    codeBlock: 'Code block',
    code: 'Code',
    horizontalRule: 'Horizontal rule',
    textColor: 'Text color',
    backgroundColor: 'Background color',
    undo: 'Undo',
    redo: 'Redo',
    removeFormat: 'Remove format',
    sourceView: 'HTML source',
    fullscreen: 'Fullscreen',
    linkDialogTitle: 'Insert link',
    linkDialogUrl: 'URL',
    linkDialogText: 'Text',
    linkDialogTarget: 'Open in new tab',
    linkDialogCancel: 'Cancel',
    linkDialogApply: 'Apply',
    imageDialogTitle: 'Insert image',
    imageUploadTab: 'Upload file',
    imageUrlTab: 'Settings',
    imageDialogUrl: 'Image URL',
    imageDialogAlt: 'Alt text',
    imageWidth: 'Width',
    imageHeight: 'Height',
    imageUploadBtn: 'Upload to server',
    imageDropHint: 'Drop an image or click to select',
    imageUploadError: 'Error uploading image',
    imageDialogCancel: 'Cancel',
    imageDialogApply: 'Insert',
    alignLeft: 'Align left',
    alignCenter: 'Center',
    alignRight: 'Align right',
    sourceDialogTitle: 'Edit HTML',
    sourceDialogCancel: 'Cancel',
    sourceDialogApply: 'Save',
    placeholder: 'Type here...',
    exportPdfTitle: 'Aracode Document',
    exportPdfEmpty: 'There is no content to export to PDF.',
    exportPdfError: 'Could not export PDF.',
    exportPdf: 'Export PDF',
    exportPdfFilename: 'documento-aracode.pdf',
    exportPdfPrintHint: 'The print dialog opened. Choose "Save as PDF" as the destination.',
  },
};

export function t(key, locale = 'es') {
  return locales[locale]?.[key] || locales.es[key] || key;
}
